capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todolist.urls'))
]

capstone/todolist/urls.py
from django.urls import path
from . import views
app_name="todolist"
urlpatterns=[
    path('',views.index,name="index"),
    path('login/',views.login_view,name="login"),
    path('register/',views.register_view,name="register"),
    path('logout',views.logout_view,name="logout"),
    path('add_task/',views.add_task_view,name="add_task"),
    path('task/<int:todoitem_id>/',views.todoitem_view,name="viewtodoitem"),
    path('task/<int:todoitem_id>/delete/',views.delete_todoitem,name="delete_task"),
    path('task/<int:todoitem_id>/edit/',views.update_todotask,name="update_task"),
    path('add_event/',views.add_event_view,name="add_event"),
    path('event/<int:eventitem_id>/',views.eventitem_view,name="vieweventitem"),
    path('event/<int:eventitem_id>/delete/',views.delete_eventitem,name="delete_event"),
    path('event/<int:eventitem_id>/edit/',views.update_eventtask,name="update_event"),
    path('updateprofile/',views.update_profile,name="update_profile"),
]

capstone/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ToDoApp{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

capstone/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">ToDoApp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-lg-flex justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'todolist:index' %}">Home</a>
          </li>
          {% if user.is_anonymous != True %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:add_event' %}">Add Event</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:update_profile' %}">Update Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-warning rounded" href="{% url 'todolist:logout' %}">Logout</a>
            </li>
          {% endif %}
          {% if user.is_anonymous == True %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>