capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todolist.urls'))
]

capstone/todolist/urls.py
from django.urls import path
from . import views
app_name="todolist"
urlpatterns=[
    path('',views.index,name="index"),
    path('login/',views.login_view,name="login"),
    path('register/',views.register_view,name="register"),
    path('logout',views.logout_view,name="logout"),
    path('add_task/',views.add_task_view,name="add_task"),
    path('task/<int:todoitem_id>/',views.todoitem_view,name="viewtodoitem"),
    path('task/<int:todoitem_id>/delete/',views.delete_todoitem,name="delete_task"),
    path('task/<int:todoitem_id>/edit/',views.update_todotask,name="update_task"),
    path('add_event/',views.add_event_view,name="add_event"),
    path('event/<int:eventitem_id>/',views.eventitem_view,name="vieweventitem"),
    path('event/<int:eventitem_id>/delete/',views.delete_eventitem,name="delete_event"),
    path('event/<int:eventitem_id>/edit/',views.update_eventtask,name="update_event"),
    path('updateprofile/',views.update_profile,name="update_profile"),
]

capstone/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class ToDoItem(models.Model):
    task_name=models.CharField(max_length=50)
    description=models.CharField(max_length=200)
    status=models.CharField(max_length=50,default="pending")
    data_created=models.DateTimeField("date created:")
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.task_name
class EventItem(models.Model):
    event_name=models.CharField(max_length=100)
    description=models.CharField(max_length=200)
    status=models.CharField(max_length=50,default="Coming")
    event_date=models.DateTimeField("event date")
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.event_name

capstone/todolist/forms.py
from django import forms

class RegisterForm(forms.Form):
    username=forms.CharField(label="username",max_length=50)
    first_name=forms.CharField(label="first_name",max_length=50)
    last_name=forms.CharField(label="last_name",max_length=50)
    email=forms.CharField(label="email",max_length=50)
    password=forms.CharField(label="password",max_length=50)
    confirm_password=forms.CharField(label="confirm_password",max_length=50)

class LoginForm(forms.Form):
    username=forms.CharField(label='username',max_length=50)
    password=forms.CharField(label='password',max_length=50)

class AddTaskForm(forms.Form):
    task_name=forms.CharField(label='task_name',max_length=50)
    description=forms.CharField(label='description',max_length=200)

class UpdateTaskForm(forms.Form):
    task_name=forms.CharField(label='task_name',max_length=50)
    description=forms.CharField(label='description',max_length=200)
    status=forms.CharField(label='status',max_length=50)

class AddEventForm(forms.Form):
    event_name=forms.CharField(label='event_name',max_length=100)
    description=forms.CharField(label='description',max_length=200)
    event_date=forms.DateTimeField(label='event_date')

class UpdateEventForm(forms.Form):
    event_name=forms.CharField(label='event_name',max_length=100)
    description=forms.CharField(label='description',max_length=200)
    event_date=forms.DateTimeField(label='event_date')
    status=forms.CharField(label='status',max_length=50)
class UpdateProfile(forms.Form):
    previous_password=forms.CharField(label='previous_password',max_length=50)
    password=forms.CharField(label="password",max_length=50)
    confirm_password=forms.CharField(label="confirm_password",max_length=50)

capstone/todolist/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import RegisterForm,LoginForm,AddTaskForm,UpdateTaskForm,AddEventForm,UpdateEventForm,UpdateProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .models import ToDoItem,EventItem
from django.utils import timezone
from django.forms.models import model_to_dict
def index(request):
    if request.user.is_anonymous:
        return redirect('todolist:login')
    else:
        todoitem=ToDoItem.objects.filter(user_id=request.user.id)
        eventitem=EventItem.objects.filter(user_id=request.user.id)
        context={
            'user':request.user,
            'todoitem':todoitem,
            'eventitem':eventitem
        }
    return render(request,"todolist/index.html",context)
def login_view(request):
    context={}
    if request.method == "POST":
        form=LoginForm(request.POST)
        if form.is_valid()==False:
            form=LoginForm()
            context={
                'error':True
            }
        else:
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(username=username,password=password)
            context={
                "username":username,
                "password":password,
            }
            if user is not None:
                login(request,user)
                return redirect("todolist:index")
            else:
                context={
                    'error':True
                }
    return render(request,"todolist/signin.html",context)
def register_view(request):
    is_user_registered=False
    users=User.objects.all()
    context={

    }
    if (request.method == "POST"):
        context={
        'error':True
        }
        form=RegisterForm(request.POST)
        if form.is_valid()== False:
            form=RegisterForm()
        else:
            password=form.cleaned_data['password']
            confirm_password=form.cleaned_data['confirm_password']
            if(password==confirm_password):
                user=User()
                username=form.cleaned_data['username']
                email=form.cleaned_data['email']
                first_name=form.cleaned_data['first_name']
                last_name=form.cleaned_data['last_name']
                user.username=username
                user.first_name=first_name
                user.last_name=last_name
                user.email=email
                user.is_active=True
                user.is_staff=False
                for indiv_user in users:
                    if(indiv_user.username==user.username):
                        is_user_registered=True
                if(is_user_registered==False):
                    context={
                        'error':False
                    }
                    user.set_password(password)
                    user.save()
                    return redirect("todolist:login")
    return render(request,"todolist/register.html",context)
def logout_view(request):
    logout(request)
    return redirect('todolist:login')
def add_task_view(request):
    if request.user.is_anonymous:
        return redirect('todolist:login')
    else:
        context={}
        if(request.method=="POST"):
            form=AddTaskForm(request.POST)
            if(form.is_valid()==False):
                context={
                    'error':True
                }
                form=AddTaskForm()
            else:
                task_name=form.cleaned_data['task_name']
                description=form.cleaned_data['description']
                duplicates=ToDoItem.objects.filter(task_name=task_name)
                if not duplicates:
                    ToDoItem.objects.create(task_name=task_name,description=description,data_created=timezone.now(),user_id=request.user.id)
                    return redirect('todolist:index')
                else:
                    context={
                        'error':True
                    }
        return render(request,'todoList/add_task.html',context)
def todoitem_view(request,todoitem_id):
    if request.user.is_anonymous:
        return redirect('todolist:login')
    else:
        item=get_object_or_404(ToDoItem,pk=todoitem_id)
        return render(request,'todolist/viewtodoitem.html',model_to_dict(item))      
def delete_todoitem(request,todoitem_id):
    if request.user.is_anonymous:
        return redirect("todolist:login")
    else:
        ToDoItem.objects.filter(pk=todoitem_id).delete()
        return redirect("todolist:index")
def update_todotask(request,todoitem_id):
    if request.user.is_anonymous:
        return redirect("todolist:login")
    else:
        item=ToDoItem.objects.filter(pk=todoitem_id)
        context={
            'task_name':item[0].task_name,
            'description':item[0].description,
            'status':item[0].status,
        }
        if(request.method=="POST"):
            form=UpdateTaskForm(request.POST)
            if(form.is_valid()==False):
                form=UpdateTaskForm()
                context={
                    'error':True
                }
            else:
                task_name=form.cleaned_data['task_name']
                description=form.cleaned_data['description']
                status=form.cleaned_data['status']
                if item:
                    item[0].task_name=task_name
                    item[0].description=description
                    item[0].status=status
                    item[0].save()
                    return redirect("todolist:index")
                else:
                    context={
                        'error':True
                    }

        return render(request,'todolist/updatetask.html',context)

def add_event_view(request):
    if request.user.is_anonymous:
        return redirect('todolist:login')
    else:
        context={}
        if(request.method=="POST"):
            form=AddEventForm(request.POST)
            if(form.is_valid()==False):
                form=AddEventForm()
                context={
                    'error':True,
                    'msg':"Form Invalid"
                }
            else:
                event_name=form.cleaned_data['event_name']
                description=form.cleaned_data['description']
                event_date=form.cleaned_data['event_date']
                duplicates=EventItem.objects.filter(event_name=event_name)
                if not duplicates:
                    EventItem.objects.create(event_name=event_name,description=description,event_date=event_date,user_id=request.user.id)
                    return redirect("todolist:index")
                else:
                    context={
                        'error':True,
                        'msg':"Duplicates Event"
                    }
        return render(request,'todolist/add_event.html',context)
def eventitem_view(request,eventitem_id):
    if request.user.is_anonymous:
        return redirect("todolist:login")
    else:
        eventitem=get_object_or_404(EventItem,pk=eventitem_id)
        return render(request,'todolist/vieweventitem.html',model_to_dict(eventitem))
def delete_eventitem(request,eventitem_id):
    if request.user.is_anonymous:
        return redirect("todolist:login")
    else:
        EventItem.objects.filter(pk=eventitem_id).delete()
        return redirect("todolist:index")
def update_eventtask(request,eventitem_id):
    if request.user.is_anonymous:
        return render("todolist:login")
    else:
        item=EventItem.objects.filter(pk=eventitem_id)
        context={
            'event_name':item[0].event_name,
            'description':item[0].description,
            'status':item[0].status,
            'event_date':item[0].event_date
        }
        if(request.method=="POST"):
            form=UpdateEventForm(request.POST)
            if(form.is_valid()==False):
                form=UpdateEventForm()
                context={
                    'error':True
                }
            else:
                event_name=form.cleaned_data['event_name']
                description=form.cleaned_data['description']
                event_date=form.cleaned_data['event_date']
                status=form.cleaned_data['status']
                if item:
                    item[0].event_name=event_name
                    item[0].description=description
                    item[0].event_date=event_date
                    item[0].status=status
                    item[0].save()
                    return redirect("todolist:index")
                else:
                    context={
                        'error':True
                    }
        return render(request,'todolist/update_event.html',context)
def update_profile(request):
    if(request.user.is_anonymous):
        return redirect("todolist:login")
    else:
        context={
            'error':False,
            'msg':"",
            'username':request.user.username,
            'first_name':request.user.first_name,
            'last_name':request.user.last_name,
            'email':request.user.email,
        }
        if(request.method=="POST"):
            form=UpdateProfile(request.POST)
            if(form.is_valid()==False):
                form=UpdateProfile()
                context={
                    'error':True,
                    'msg':"Form is invalid! Try Again",
                    'username':request.user.username,
                    'first_name':request.user.first_name,
                    'last_name':request.user.last_name,
                    'email':request.user.email,
                    }
            else:
                previous_password=form.cleaned_data['previous_password']
                password=form.cleaned_data['password']
                confirm_password=form.cleaned_data['confirm_password']

capstone/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}
{% block title %}Add Event{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Add A Event</h1>
            {% if error == True %}
                <p class="text-danger">{{msg}}</p>
            {% endif %}
            <form action="{% url 'todolist:add_event' %}" method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="event_name">Event Name: </label>
                    <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
                </div>

                <div class="mb-3">
                    <label for="description">Description: </label>
                    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                </div>
                <div class="mb-3">
                    <label for="date">Event Date: </label>
                    <input class="form-control" id="date" type="date" name="event_date" required>
                </div>
                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Add Event">
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}

capstone/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}
{% block title %}Add Task{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Add A Task</h1>
            {% if error == True %}
                <p class="text-danger">Duplicate task found</p>
            {% endif %}
            <form action="{% url 'todolist:add_task' %}" method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="task_name">Task Name: </label>
                    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
                </div>

                <div class="mb-3">
                    <label for="description">Description: </label>
                    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                </div>

                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Add Task">
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}

capstone/todolist/templates/todolist/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    {% if user.is_anonymous == True %}
    <div>
        <p class="text-center">It's appear you are not sign in.<a href="{% url 'todolist:login' %}">Click Here</a></p>
    </div>
    {% else %}
    <h1 class="text-center">Welcome {{user.first_name}} {{user.last_name}}</h1>
    <div class="d-flex justify-content-center mb-2">
        <div class="list-group" style="width: 400px;">
            <h4 class="text-center">My Task</h4>
            {% if todoitem.count == 0 %}
                <a href="{% url 'todolist:add_task' %}" class="list-group-item list-group-item-action bg-warning" aria-current="true">
                    <h5 class="text-center">Add Task</h5>
                </a>
            {% else %}
                {% for items in todoitem %}
                    <a href="{% url 'todolist:viewtodoitem' items.id %}" class="list-group-item list-group-item-action" aria-current="true">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{items.task_name}}</h5>
                        </div>
                        <small><strong>Status: </strong>{{items.status}}</small>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="list-group" style="width: 400px;">
            <h4 class="text-center">My Events</h4>
            {% if eventitem.count == 0 %}
                <a href="{% url 'todolist:add_event' %}" class="list-group-item list-group-item-action bg-warning" aria-current="true">
                    <h5 class="text-center">Add Event</h5>
                </a>
            {% else %}
                {% for eitems in eventitem %}
                    <a href="{% url 'todolist:vieweventitem' eitems.id %}" class="list-group-item list-group-item-action" aria-current="true">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{eitems.event_name}}</h5>
                        </div>
                        <small><strong>Status: </strong>{{eitems.status}}</small>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endif %}
{% endblock %}

capstone/todolist/templates/todolist/register.html
{% extends 'base.html' %}
{% block title %}Sign In{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Register</h1>
            {% if error == True %}
                <p class="text-danger">Invalid user credentials, please check your username and password</p>
            {% endif %}
            <form action="{% url 'todolist:register' %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username">Username: </label>
                    <input class="form-control" id="username" type="text" name="username" maxlength="20" required>
                </div>

                <div class="mb-3">
                    <label for="first_name">First Name: </label>
                    <input class="form-control" id="first_name" type="text" name="first_name" maxlength="50" required>
                </div>

                <div class="mb-3">
                    <label for="last_name">Last Name: </label>
                    <input class="form-control" id="last_name" type="text" name="last_name" maxlength="50" required>
                </div>

                <div class="mb-3">
                    <label for="email">Email: </label>
                    <input class="form-control" id="email" type="email" name="email" maxlength="100" required>
                </div>

                <div class="mb-3">
                    <label for="password">Password: </label>
                    <input class="form-control" id="password" type="password" name="password" maxlength="20" required>
                </div>

                <div class="mb-3">
                    <label for="confirm_password">Confirm Password: </label>
                    <input class="form-control" id="confirm_password" type="password" name="confirm_password" maxlength="20" required>
                </div>

                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Register">
                </div>
            </form>
            <p class="text-center mt-2">Account created,<a href="{% url 'todolist:login' %}">Click Here</a></p>
        </div>
    </div>
</div>
{% endblock %}

capstone/todolist/templates/todolist/signin.html
{% extends 'base.html' %}
{% block title %}Sign In{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Login</h1>
            {% if error == True %}
                <p class="text-danger">Invalid user credentials, please check your username and password</p>
            {% endif %}
            <form action="{% url 'todolist:login' %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username">Username: </label>
                    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="password">Password: </label>
                    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
                </div>
                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Login">
                </div>
            </form>
            <p class="text-center mt-2">Create new accout,<a href="{% url 'todolist:register' %}">Click Here</a></p>
        </div>
    </div>
</div>
{% endblock %}

capstone/todolist/templates/todolist/update_event.html
{% extends 'base.html' %}
{% block title %}Update Task{% endblock %}
{% block content %}
	<div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">Update Event</h1>
                    {% if error == True %}
                        <p class="text-danger">Event not found</p>
                    {% endif %}
                    <form action="#" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="event_name">Event Name: </label>
                            <input class="form-control" id="event_name" type="text" name="event_name" value="{{event_name}}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" required>{{ description }}</textarea>
                        </div>

                         <div class="mb-3">
                            <label for="event_date">Event Date: </label>
                            <input class="form-control" id="event_date" type="date" name="event_date" value="{{event_date}}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="status">Status: </label>
                            <input class="form-control" id="status" type="text" name="status" value="{{status}}" maxlength="50" required>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Update Event">
                        </div>

                    </form>
                </div>
            </div>
    </div>
{% endblock %}

capstone/todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="container rounded bg-white mt-5">
        <div class="row">
            <div class="col-md-4 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" src="https://i.imgur.com/0eg0aG0.jpg" width="90"><span class="font-weight-bold">{{username}}</span><span class="text-black-50">{{email}}</span></div>
            </div>
            <div class="col-md-8">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <div class="d-flex flex-row align-items-center back"><i class="fa fa-long-arrow-alt-left"></i>
                            <h6 class="mt-2"><a href="{% url 'todolist:index' %}" style="color:black;text-decoration: none;">Back to home</a></h6>
                        </div>
                        <h6 class="text-right">Edit Profile</h6>
                    </div>
                    {% if error == True %}
                        <p class="text-danger text-center">Event not found</p>
                      {% endif %}
                    <form action="{% url 'todolist:update_profile' %}" method="post">
                      {% csrf_token %}
                      <div class="row mt-2">
                        <div class="col-md-6"><input type="text" class="form-control" value="{{first_name}}" disabled></div>
                        <div class="col-md-6"><input type="text" class="form-control" value="{{last_name}}" disabled></div>
                      </div>
                      <div class="row mt-3">
                          <div class="col-md-6"><input type="email" class="form-control" placeholder="Email" value="{{email}}" disabled></div>
                      </div>
                      <div class="row mt-3">
                          <div class="col-md-6"><input type="password" name="previous_password" class="form-control" placeholder="Current Password"></div>
                      </div>
                      <div class="row mt-2">
                          <div class="col-md-6"><input type="password" name="password" class="form-control" placeholder="New Password"></div>
                          <div class="col-md-6"><input type="password" name="confirm_password" class="form-control" placeholder="Confirm Password"></div>
                      </div>
                      <div class="mt-3 text-right"><input class="btn btn-danger profile-button" type="submit" value="Change"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

capstone/todolist/templates/todolist/updatetask.html
{% extends 'base.html' %}
{% block title %}Update Task{% endblock %}
{% block content %}
	<div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">Update Task</h1>
                    {% if error == True %}
                        <p class="text-danger">Task not found</p>
                    {% endif %}
                    <form action="#" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="task_name">Task Name: </label>
                            <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" required>{{ description }}</textarea>
                        </div>


                        <div class="mb-3">
                            <label for="status">Status: </label>
                            <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Update Task">
                        </div>

                    </form>
                </div>
            </div>
    </div>
{% endblock %}

capstone/todolist/templates/todolist/vieweventitem.html
{% extends 'base.html' %}
{% block title %}Event{% endblock %}
{% block content %}
<div class="row d-flex justify-content-center p-4">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{event_name}}</h5>
        <p class="card-text">{{description}}</p>
        <p class="card-text"><strong>Status: </strong>{{status}}</p>
        <p class="card-text"><strong>Time: </strong>{{event_date}}</p>
        <a href="{% url 'todolist:index' %}" class="btn btn-primary">Back</a>
        <a href="{% url 'todolist:update_event' id %}" class="btn btn-warning">Edit</a>
        <a href="{% url 'todolist:delete_event' id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

capstone/todolist/templates/todolist/viewtodoitem.html
{% extends 'base.html' %}
{% block title %}Task{% endblock %}
{% block content %}
<div class="row d-flex justify-content-center p-4">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{task_name}}</h5>
        <p class="card-text">{{description}}</p>
        <p class="card-text"><strong>Status: </strong>{{status}}</p>
        <a href="{% url 'todolist:index' %}" class="btn btn-primary">Back</a>
        <a href="{% url 'todolist:update_task' id %}" class="btn btn-warning">Edit</a>
        <a href="{% url 'todolist:delete_task' id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}